baseURL = 'https://kev-in-ta.github.io'
languageCode = 'en-us'
title = 'kev-in-ta.github.io'
theme = "kelvinkoondev_v2"
pygmentsCodefences = true
pygmentsStyle = "pygments"
defaultContentLanguage = "en"

[params]
  name = "Kevin Ta"
  github = "https://github.com/kev-in-ta"
  linkedin = "https://www.linkedin.com/in/kevinjhyta"
  scholar = "https://scholar.google.com/citations?user=npFtagoAAAAJ&hl=en"
  instagram = "https://instagram.com/kta.climbs"
  source = "https://github.com/kev-in-ta/kev-in-ta.github.io"
  quote = "I know I am a writer because until I'm writing I don't know what I know."
  quoteauthor = "- Wayson Choy, Author of All That Matters"
