baseURL = 'https://kev-in-ta.github.io'
languageCode = 'en-us'
title = 'kev-in-ta.github.io'
theme = "kelvinkoondev_v2"
pygmentsCodefences = true
pygmentsStyle = "pygments"
defaultContentLanguage = "en"

[params]
  name = "Kevin Ta"
  github = "https://github.com/kev-in-ta"
  linkedin = "https://www.linkedin.com/in/kevinjhyta"
  scholar = "https://scholar.google.com/citations?user=npFtagoAAAAJ&hl=en"
  instagram = "https://instagram.com/kta.climbs"
  source = "https://github.com/kev-in-ta/kev-in-ta.github.io"
  quote = "Contemplate the marvel that is existence, and rejoice that you are able to do so. I feel I have the right to tell you this because, as I am inscribing these words, I am doing the same."
  quoteauthor = "- Ted Chiang, Exhalation"
